# Setup
title:               The ICLR Blog Track
tagline:             ''
description:         'For short-term, peer-sourced tests of time, generalizations, specializations, reproductions, etc.!'
url:                 https://10605-proj.github.io/
baseurl:             ''
paginate:            5
permalink:           pretty

# github
github:
  repo: https://github.com/iclr-blog-track/iclr-blog-track.github.io

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
<<<<<<< HEAD
version:             1.1.0
google_analytics_id: UA-146052-15

theme: jekyll-theme-minimal
=======
version:             ICLR Spring 2021
google_analytics_id: #UA-XXXX-Y
>>>>>>> master
